### ISSUE TITLE
Support newest version of uuid

### ISSUE THREAD

**Issue by emeric254** [txlabs/vnodes#10]
As written in the uuid project documentation "Deep Requires Now Deprecated", so the current import `import uuid from 'uuid'` no longer work anymore

```
Failed to compile.

./node_modules/vnodes/src/graph.js 96:10-14
"export 'default' (imported as 'uuid') was not found in 'uuid'
```

I've made an attempt to fix that according to the migration section from the uuid documentation.

See my PR -> https://github.com/txlabs/vnodes/pull/9

**Comment by gr1m1um** [comment]
Merged, thanks for the PR.
