### ISSUE TITLE
Can't have node id equal to 0

### ISSUE THREAD

**Issue by plfbvr** [txlabs/vnodes#12]
When adding an edge, the `from.id` and `to.id` values are checked, and an exception is raised if one of them is equal to 0.

The corresponding line:
https://github.com/txlabs/vnodes/blob/3d489e6d22797b9f1a91d5a4ed573dd3e3e9be97/src/graph.js#L132

Why `from.id = 0` (same for `to`) would be forbidden ? Maybe those value should be compared to `null` (with `===`), so that `0` value could be allowed ?

**Comment by gr1m1um** [comment]
ids should be strings, that should fix the problem easier
