### ISSUE TITLE
Use npm svg-pan-zoom instead of embedded one

### ISSUE THREAD

**Issue by emeric254** [txlabs/vnodes#15]
Todo list :
- [x] find which version of svg-panzoom is currently used by this project
- [x] add svg-pan-zoom to this project dependencies (package.json)
- [x] test svg-pan-zoom new releases does not break anything

I'll try to come up with a PR to work on that

**Comment by emeric254** [comment]
Ok seems there was no changes on svg-pan-zoom since 2019 so we're good in that way
(https://github.com/bumbu/svg-pan-zoom/issues/395 and https://github.com/bumbu/svg-pan-zoom/releases)

**Comment by gr1m1um** [comment]
Hey, svg-pan-zoom is a customized version, that's why its embed.
I can't remember the changes but includes some global variables exposure and event changes so they can be intercepted/cancelled, possibly others, svg-pan-zoom is not ideal and the code its old but its quick to setup and use.

**Comment by emeric254** [comment]
Ok no problem good to know :+1:
