### ISSUE TITLE
Love the Benchpress in the demo site.

### ISSUE THREAD

**Issue by karx** [txlabs/vnodes#2]
It is amazing to see benchpress as part of the demo site.
Kudos!

Just posting for ref here:
On my Chrome operating around 1.7GB RAM consumption, works comfortably for 1000 nodes.

Face issue when we reach around ~2000 nodes.

**Comment by gr1m1um** [comment]
Thanks, well I haven't looked into optimization yet but there shouldn't be much to trim.
One possibility is to filter visible nodes inside the screen, that's straightforward.
Other is to filter visible edges but that needs a rectangle + line intersection detection.
Haven't tried these solutions but may help scale the number of nodes supported.

**Comment by gr1m1um** [comment]
Just updated the documentation with details about the components and how they can be used, plus some fixes.
More demos / demo improvements to come in the near future.

**Comment by karx** [comment]
> One possibility is to filter visible nodes inside the screen, that's straightforward.

This would help in a few scenario.


> Other is to filter visible edges but that needs a rectangle + line intersection detection.

This seems like it might add an unnecessary overhead, which might even affect performance for smaller graph.
Not sure the complexity of technique you have in mind for this, however, sounds like something that would be affected by "degree of connectedness" of the graph.

an optional optimization maybe then.



Kudos again tho.
