### ISSUE TITLE
Any way to input data from user?

### ISSUE THREAD

**Issue by omerfdmrl** [txlabs/vnodes#20]
Hi. Is there any way to input data from user by label or edge?

**Comment by tiagolr** [comment]
yes, data passed when creating an edge or node is passed to the component, eg:
```js
this.graph.createNode({id: 'A', customData: 'text' })
this.graph.createEdge('A', ''B', { customData: 'text' })
```
you can also set it afterwards
```
const A = this.graph.createNode('A')
A.prop = 'sometext'
```
not sure if that's what your asking but hope this answers
