### ISSUE TITLE
Vnodes is not working on Safari

### ISSUE THREAD

**Issue by scramatte** [txlabs/vnodes#21]
Hello,

Vnodes is not working on Safari Mac or Mobile:

![image](https://user-images.githubusercontent.com/188766/206898641-769b3719-2a36-40cd-bf96-05d957a94eca.png)

Can you fix it ?

Regards

**Comment by tiagolr** [comment]
Thank you for reporting, unfortunately I don't have the mac hardware to fix the problem for now so it may take a while to solve.

**Comment by scramatte** [comment]
It looks like something with your demo...

![image](https://user-images.githubusercontent.com/188766/207379831-baedf59c-b44b-411f-8a51-d49c4df7ec91.png)

With Chrome

 
![image](https://user-images.githubusercontent.com/188766/207379919-c7b6dfef-3f54-4869-9d0e-c5e4285646bc.png)
With Safari on MacOS Bigsur

As you can see only some problem with edges alignmemts.  

In all case, If you want, I can give you access to a remote MacOS hardware  to fix  any issue on these platform.
Contact me in private and I send you details.

on iOS is not working.   Edges are not connected to ports/nodes  and gestures  are not supported (for zoom for example). 
Not sure that touch event works. To handle drag and drop  it will be necesary to handle tap, long tap and something more.

![IMG_F2D57CD9E4C4-1](https://user-images.githubusercontent.com/188766/207381144-e228cfeb-9bb5-43fa-b87c-27c2cd22ce51.jpeg)

Regards

**Comment by scramatte** [comment]
It works now with Safari !  It was port styles and markup issues...
Now we need to get it working on iOS Safari but for this I'll some help from your side.

**Comment by scramatte** [comment]
I've tested it on Android and displaying is ok but touch events are not working such zoom or drag

**Comment by tiagolr** [comment]
I can try and fix android, iOS I don't have the tools, how did you fix the port styles / markup issues? maybe a PR for that, cheers

**Comment by scramatte** [comment]
About style, I believe tat was just mistake from my side as port shape must me square / circle. 
It looks that with your demo, Safari doesn't render well various diagram on the same page. 

About iOS/Mac  I can send you access to remote MacOs with all tools to fix. Including iOS simulator. So you can link Safari with simulator to get debug info you needs.

**Comment by tiagolr** [comment]
Okay, I am not sure when I'll be available but feel free to ping me, I'll be fixing the android touch events meanwhile.

**Comment by tiagolr** [comment]
okay, just fixed drag on mobile, also enabled controls for zoom on mobile devices as a workaround since pinch zoom can be tricky to add

**Comment by tiagolr** [comment]
Closing this as PR has been merged
