### ISSUE TITLE
vnodes is not woking

### ISSUE THREAD

**Issue by xtthaop** [txlabs/vnodes#24]
Uncaught SyntaxError: The requested module '/node_modules/victor/index.js?v=75e549ec' does not provide an export named 'default'

**Comment by tiagolr** [comment]
can you provide more context, what node version? Is there a sample app I can try?

**Comment by xtthaop** [comment]
> can you provide more context, what node version? Is there a sample app I can try?

node 16.17.1
npm 8.15.0
vue 3.2.47
vnodes 1.2.0

1.npm init vue@latest
2.follow the README.md
3.browser console error "The requested module '/node_modules/victor/index.js?v=75e549ec' does not provide an export named 'default'"

**Comment by tiagolr** [comment]
Thank you for noticing
Its fixed now in version 1.3.0
Also updated the readme as leaving comments (`<!-- -->`) inside nodes causes them not to render properly.
Let me know if it works for you
