### ISSUE TITLE
Removing nodes

### ISSUE THREAD

**Issue by maksim-buren** [txlabs/vnodes#3]
Why nodes remove after 1 index, in this case we can't remove 2 first nodes
`removeNode (node) {
    const index = this.nodes.indexOf(node)
    if (index > 1) {
      this.nodes.splice(index, 1)
    }
    return index
  }`

**Comment by gr1m1um** [comment]
thats odd, looking into it or at least to figure the intent, fixing this soon, thanks

**Comment by gr1m1um** [comment]
probably just a typo with the -1, removeEdge seems okay
