### ISSUE TITLE
Cannot import component Screen | Edge | Node

### ISSUE THREAD

**Issue by duydtd97** [txlabs/vnodes#6]
![image](https://user-images.githubusercontent.com/23192661/133321490-8319c506-e3a9-4089-90a8-437dc2d23403.png)

**Comment by duydtd97** [comment]
please expland to me why i can't import your components
![image](https://user-images.githubusercontent.com/23192661/133321881-711e5762-3744-4185-b853-9eff053c455a.png)

**Comment by iec989** [comment]
Did you manage to solve this @duydtd97 ?

In my case I'm getting the following error:
```
WARNING in ./node_modules/d3-flextree/src/flextree.js 172:19-26
Should not import the named export 'version' (imported as 'version') from default-exporting module (only default export is available soon)
```

**Comment by duydtd97** [comment]
not yet :( @iec989

**Comment by iec989** [comment]
There is a dependency that needs to be solved here: https://github.com/Klortho/d3-flextree/issues/21

**Comment by iec989** [comment]
@duydtd97 not sure why it doesn't work, but the following worked for me:

`import vnodes from 'vnodes';`

```
const vnodesScreen = vnodes.Screen;
const vnodesNode = vnodes.Node;
const vnodesEdge = vnodes.Edge;
const vnodesgraph = vnodes.graph;
```

```
export default {
	components: {vnodesScreen,vnodesNode,vnodesEdge},
	data () {
		return {
```

**Comment by duydtd97** [comment]
woww Amazingg Bro! It's working, thank for your help!
God bless you! 🌹 

> @duydtd97 not sure why it doesn't work, but the following worked for me:
> 
> `import vnodes from 'vnodes';`
> 
> ```
> const vnodesScreen = vnodes.Screen;
> const vnodesNode = vnodes.Node;
> const vnodesEdge = vnodes.Edge;
> const vnodesgraph = vnodes.graph;
> ```
> 
> ```
> export default {
> 	components: {vnodesScreen,vnodesNode,vnodesEdge},
> 	data () {
> 		return {
> ```

**Comment by duydtd97** [comment]
I have a question. I don't want using dragging. Could it disable dragging? @iec989

**Comment by iec989** [comment]
Just set the prop useDrag as false

https://github.com/txlabs/vnodes/blob/master/src/components/Node.vue

**Comment by duydtd97** [comment]
wow, thank you very much bro! @iec989
